=begin
#Custom Workflow Actions

#Create custom workflow actions

The version of the OpenAPI document: v4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Hubspot::Automation::Actions::RevisionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RevisionsApi' do
  before do
    # run before each test
    @api_instance = Hubspot::Automation::Actions::RevisionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RevisionsApi' do
    it 'should create an instance of RevisionsApi' do
      expect(@api_instance).to be_instance_of(Hubspot::Automation::Actions::RevisionsApi)
    end
  end

  # unit tests for get_by_id
  # Get a revision for a custom action
  # Returns the given version of a custom workflow action.
  # @param definition_id The ID of the custom workflow action.
  # @param revision_id The version of the custom workflow action.
  # @param app_id 
  # @param [Hash] opts the optional parameters
  # @return [ActionRevision]
  describe 'get_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_page
  # Get all revisions for a custom action
  # Returns a list of revisions for a custom workflow action.
  # @param definition_id The ID of the custom workflow action
  # @param app_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Maximum number of results per page.
  # @option opts [String] :after The paging cursor token of the last successfully read resource will be returned as the &#x60;paging.next.after&#x60; JSON property of a paged response containing more results.
  # @return [CollectionResponseActionRevisionForwardPaging]
  describe 'get_page test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
