=begin
#Transactional Email

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Hubspot::Marketing::Transactional::CollectionResponseSmtpApiTokenViewForwardPaging
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CollectionResponseSmtpApiTokenViewForwardPaging' do
  before do
    # run before each test
    @instance = Hubspot::Marketing::Transactional::CollectionResponseSmtpApiTokenViewForwardPaging.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CollectionResponseSmtpApiTokenViewForwardPaging' do
    it 'should create an instance of CollectionResponseSmtpApiTokenViewForwardPaging' do
      expect(@instance).to be_instance_of(Hubspot::Marketing::Transactional::CollectionResponseSmtpApiTokenViewForwardPaging)
    end
  end
  describe 'test attribute "results"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "paging"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
