=begin
#Accounting Extension

#These APIs allow you to interact with HubSpot's Accounting Extension. It allows you to: * Specify the URLs that HubSpot will use when making webhook requests to your external accounting system. * Respond to webhook calls made to your external accounting system by HubSpot 

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Hubspot::Crm::Extensions::Accounting::SettingsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SettingsApi' do
  before do
    # run before each test
    @api_instance = Hubspot::Crm::Extensions::Accounting::SettingsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SettingsApi' do
    it 'should create an instance of SettingsApi' do
      expect(@api_instance).to be_instance_of(Hubspot::Crm::Extensions::Accounting::SettingsApi)
    end
  end

  # unit tests for get_by_id
  # Get URL settings
  # Returns the URL settings for an accounting app with the specified ID.
  # @param app_id The ID of the accounting app. This is the identifier of the application created in your HubSpot developer portal.
  # @param [Hash] opts the optional parameters
  # @return [AccountingAppSettings]
  describe 'get_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replace
  # Add/Update URL Settings
  # Add/Update the URL settings for an accounting app with the specified ID.  All URLs must use the &#x60;https&#x60; protocol.
  # @param app_id The ID of the accounting app. This is the identifier of the application created in your HubSpot developer portal.
  # @param accounting_app_settings 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'replace test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
