=begin
#CMS Audit Logs

#Use this endpoint to query audit logs of CMS changes that occurred on your HubSpot account.

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Hubspot::Cms::AuditLogs::AuditLogsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AuditLogsApi' do
  before do
    # run before each test
    @api_instance = Hubspot::Cms::AuditLogs::AuditLogsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuditLogsApi' do
    it 'should create an instance of AuditLogsApi' do
      expect(@api_instance).to be_instance_of(Hubspot::Cms::AuditLogs::AuditLogsApi)
    end
  end

  # unit tests for get_page
  # Query audit logs
  # Returns audit logs based on filters.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :object_id Comma separated list of object ids to filter by.
  # @option opts [Array<String>] :user_id Comma separated list of user ids to filter by.
  # @option opts [String] :after Timestamp after which audit logs will be returned
  # @option opts [String] :before Timestamp before which audit logs will be returned
  # @option opts [Array<String>] :sort The sort direction for the audit logs. (Can only sort by timestamp).
  # @option opts [Array<String>] :event_type Comma separated list of event types to filter by (CREATED, UPDATED, PUBLISHED, DELETED, UNPUBLISHED).
  # @option opts [Integer] :limit The number of logs to return.
  # @option opts [Array<String>] :object_type Comma separated list of object types to filter by (BLOG, LANDING_PAGE, DOMAIN, HUBDB_TABLE etc.)
  # @return [CollectionResponsePublicAuditLog]
  describe 'get_page test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
