=begin
#OAuthService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'

# Unit tests for Hubspot::OAuth::RefreshTokensApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RefreshTokensApi' do
  before do
    # run before each test
    @instance = Hubspot::OAuth::RefreshTokensApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RefreshTokensApi' do
    it 'should create an instance of RefreshTokensApi' do
      expect(@instance).to be_instance_of(Hubspot::OAuth::RefreshTokensApi)
    end
  end

  # unit tests for deleteoauthv1refresh_tokenstoken
  # Auth Level: none ([Docs](https://product.hubteam.com/docs/appsystems/auth-and-rest/auth-levels.html)) [Source Code](https://private.hubteam.com/opengrok/search?project&#x3D;all&amp;path&#x3D;RefreshTokensResource%20OR%20Object&amp;defs&#x3D;deleteRefreshToken)&amp;nbsp;|&amp;nbsp;[API Goggles](https://tools.hubteam.com/api/delete/api.hubapi.com%2Foauth%2Fv1%2Frefresh-tokens%2F%28%28%7Btoken%7D%29%29?showRequestDetails&#x3D;true)&amp;nbsp;|&amp;nbsp;&lt;a href&#x3D;&#39;#operations-Refresh_Tokens-delete-%2Foauth%2Fv1%2Frefresh-tokens%2F%7Btoken%7D&#39;&gt;Permalink&lt;/a&gt;
  # @param token 
  # @param [Hash] opts the optional parameters
  # @return [Error]
  describe 'deleteoauthv1refresh_tokenstoken test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for getoauthv1refresh_tokenshubshub_idclientsclient_id
  # Auth Level: none ([Docs](https://product.hubteam.com/docs/appsystems/auth-and-rest/auth-levels.html)) [Source Code](https://private.hubteam.com/opengrok/search?project&#x3D;all&amp;path&#x3D;RefreshTokensResource%20OR%20Object&amp;defs&#x3D;getRefreshTokenInfo)&amp;nbsp;|&amp;nbsp;[API Goggles](https://tools.hubteam.com/api/get/api.hubapi.com%2Foauth%2Fv1%2Frefresh-tokens%2Fhubs%2F%28%28%7BhubId%7D%29%29%2Fclients%2F%28%28%7BclientId%7D%29%29?showRequestDetails&#x3D;true)&amp;nbsp;|&amp;nbsp;&lt;a href&#x3D;&#39;#operations-Refresh_Tokens-get-%2Foauth%2Fv1%2Frefresh-tokens%2Fhubs%2F%7BhubId%7D%2Fclients%2F%7BclientId%7D&#39;&gt;Permalink&lt;/a&gt;
  # @param hub_id 
  # @param client_id 
  # @param [Hash] opts the optional parameters
  # @return [Array<RefreshToken>]
  describe 'getoauthv1refresh_tokenshubshub_idclientsclient_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for getoauthv1refresh_tokenshubshub_idclientsclient_idaudits
  # Auth Level: none ([Docs](https://product.hubteam.com/docs/appsystems/auth-and-rest/auth-levels.html)) [Source Code](https://private.hubteam.com/opengrok/search?project&#x3D;all&amp;path&#x3D;RefreshTokensResource%20OR%20Object&amp;defs&#x3D;getTokenAuditsByHubAndClient)&amp;nbsp;|&amp;nbsp;[API Goggles](https://tools.hubteam.com/api/get/api.hubapi.com%2Foauth%2Fv1%2Frefresh-tokens%2Fhubs%2F%28%28%7BhubId%7D%29%29%2Fclients%2F%28%28%7BclientId%7D%29%29%2Faudits?showRequestDetails&#x3D;true)&amp;nbsp;|&amp;nbsp;&lt;a href&#x3D;&#39;#operations-Refresh_Tokens-get-%2Foauth%2Fv1%2Frefresh-tokens%2Fhubs%2F%7BhubId%7D%2Fclients%2F%7BclientId%7D%2Faudits&#39;&gt;Permalink&lt;/a&gt;
  # @param hub_id 
  # @param client_id 
  # @param [Hash] opts the optional parameters
  # @return [Array<JsonNode>]
  describe 'getoauthv1refresh_tokenshubshub_idclientsclient_idaudits test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for getoauthv1refresh_tokenstoken
  # Auth Level: none ([Docs](https://product.hubteam.com/docs/appsystems/auth-and-rest/auth-levels.html)) [Source Code](https://private.hubteam.com/opengrok/search?project&#x3D;all&amp;path&#x3D;RefreshTokensResource%20OR%20Object&amp;defs&#x3D;requestRefreshTokenInfo)&amp;nbsp;|&amp;nbsp;[API Goggles](https://tools.hubteam.com/api/get/api.hubapi.com%2Foauth%2Fv1%2Frefresh-tokens%2F%28%28%7Btoken%7D%29%29?showRequestDetails&#x3D;true)&amp;nbsp;|&amp;nbsp;&lt;a href&#x3D;&#39;#operations-Refresh_Tokens-get-%2Foauth%2Fv1%2Frefresh-tokens%2F%7Btoken%7D&#39;&gt;Permalink&lt;/a&gt;
  # @param token 
  # @param [Hash] opts the optional parameters
  # @return [RefreshTokenInfoResponse]
  describe 'getoauthv1refresh_tokenstoken test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for getoauthv1refresh_tokenstokenaudits
  # Auth Level: none ([Docs](https://product.hubteam.com/docs/appsystems/auth-and-rest/auth-levels.html)) [Source Code](https://private.hubteam.com/opengrok/search?project&#x3D;all&amp;path&#x3D;RefreshTokensResource%20OR%20Object&amp;defs&#x3D;getTokenAudits)&amp;nbsp;|&amp;nbsp;[API Goggles](https://tools.hubteam.com/api/get/api.hubapi.com%2Foauth%2Fv1%2Frefresh-tokens%2F%28%28%7Btoken%7D%29%29%2Faudits?showRequestDetails&#x3D;true)&amp;nbsp;|&amp;nbsp;&lt;a href&#x3D;&#39;#operations-Refresh_Tokens-get-%2Foauth%2Fv1%2Frefresh-tokens%2F%7Btoken%7D%2Faudits&#39;&gt;Permalink&lt;/a&gt;
  # @param token 
  # @param [Hash] opts the optional parameters
  # @return [Array<JsonNode>]
  describe 'getoauthv1refresh_tokenstokenaudits test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
