source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem 'rails', '~> 5.2.3'
gem 'puma', '~> 4.3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jbuilder', '~> 2.5'
gem 'mysql2', '~> 0.5.2'
gem 'hubspot-api-client', path: '../../'

group :development, :test do
  gem 'pry'
  gem 'pry-byebug'
  gem 'dotenv-rails', require: 'dotenv/rails-now'
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~> 3.5'
  gem 'capybara'
  gem 'capybara-mechanize', '~> 1.11'
  gem 'selenium-webdriver', '3.4.3'
  gem 'geckodriver-helper'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
end

group :test do
  gem 'database_cleaner'
  gem 'faraday', '~> 0.17.1'
  gem 'faker', :git => 'https://github.com/faker-ruby/faker.git', :branch => 'master'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
