=begin
#FormsExternalService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Hubspot::Marketing::Forms::LegalConsentOptionsNone
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LegalConsentOptionsNone' do
  before do
    # run before each test
    @instance = Hubspot::Marketing::Forms::LegalConsentOptionsNone.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LegalConsentOptionsNone' do
    it 'should create an instance of LegalConsentOptionsNone' do
      expect(@instance).to be_instance_of(Hubspot::Marketing::Forms::LegalConsentOptionsNone)
    end
  end
  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["none"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.type = value }.not_to raise_error
      # end
    end
  end

end
